import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { getHeapCodeStatistics } from 'v8'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Row from '../components/Row'
import requests from '../requests'
import {Movie} from '../typing'

interface Props{
  tvDiscover:Movie[],
  movieDiscover:Movie[],
  todayAll:Movie[],
  bestRate:Movie[]
}

const Home = ({tvDiscover, movieDiscover, todayAll,bestRate}:Props) => {

  const [data,setData] = useState <null|[]> ([])
  


  return (
    <div className='relative bg-gradient-to-b  h-full '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
    <Header />
    <Hero category={movieDiscover} />
    <Row category={tvDiscover} title="Tendances actuelles"/>
    <Row category={todayAll} title="Tendances d'aujourd'hui"/>
    <Row category={bestRate} title="Les mieux notés" />
 
    </div>
   
  )
}

export default Home

export const getServerSideProps = async() =>{

  const [
    getTvDiscover,
    getMovieDiscover,
    getTodayAll,
    getBestRate
  ]
  = await Promise.all(
    [
      fetch(requests.fetchTvDiscover).then(res => res.json()),
      fetch(requests.fetchMovieDiscover).then(res => res.json()),
      fetch(requests.fetchTodayAll).then(res=> res.json()),
      fetch(requests.fetchBestRate).then(res => res.json())
    ]
  )
  return{
    props:{
      tvDiscover:getTvDiscover.results,
      movieDiscover:getMovieDiscover.results,
      todayAll:getTodayAll.results,
      bestRate:getBestRate.results
    }
  }

}
