import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Header from '../components/Header'
import requests from '../requests'


const Home: NextPage = () => {

  const [data,setData] = useState <null|[]> ([])


useEffect (() => {
fetch(requests.fetchTvDiscover).then(res => res.json())
.then(data => setData(data))


},[setData])
 

  
    console.log(data)


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header/>
    </div>
  )
}

export default Home
